const OVERFLOW_UNSET = 'unset';
const OVERFLOW_HIDDEN = 'hidden';
const TOKEN = 'token';
const ALREADY_EXIST_MESSAGE = 'ALREADY_EXIST';

export { OVERFLOW_HIDDEN, OVERFLOW_UNSET, TOKEN, ALREADY_EXIST_MESSAGE };
